In [1]:
import numpy as np

In [2]:
# From Python Lists
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print (arr)
print (arr_2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [4]:
# Special Arrays
print (np.zeros((3, 3)))
print (np.ones((2, 4)))
print (np.eye(3))
print (np.arange(0, 10, 2))
print (np.linspace(0, 1, 5))
print (np.random.rand(3, 2))
print (np.random.randn(3, 2))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.67358161 0.0449972 ]
 [0.71927925 0.64078141]
 [0.11258959 0.43778899]]
[[ 0.38913141 -0.90682903]
 [-1.29050036  0.06545055]
 [ 1.29077045  0.90624737]]


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(2, 3)
2
6
int64


In [8]:
# Basic Math
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print (a + b)
print (a * b)
print (np.sin(a))


[5 7 9]
[ 4 10 18]
[0.84147098 0.90929743 0.14112001]


In [9]:
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print (np.dot(A,B))
print (A @ B)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [10]:
# Aggregation
arr = np.array([1, 2, 3, 4])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())


10
2.5
4
1
1.118033988749895


In [11]:
# 1D Arrays
arr = np.array([1, 2, 3, 4, 5])
print (arr[0])
print(arr[1:4])
print(arr[::2])


1
[2 3 4]
[1 3 5]


In [12]:
# 2D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])
print(arr[:, 1])
print(arr[1, :2])


2
[2 5]
[4 5]


In [13]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print(arr[mask])


[4 5]


In [14]:
# Reshape
arr = np.arange(6)
print(arr.reshape(2, 3))


[[0 1 2]
 [3 4 5]]


In [15]:
# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))


[1 2 3 4]


In [17]:
# Stacking
print (np.vstack((a, b)))
print (np.hstack((a, b)))


[[1 2]
 [3 4]]
[1 2 3 4]


In [18]:
a = np.array([1, 2, 3])
print (a + 5)  # [6, 7, 8]


[6 7 8]


In [22]:
# Save to a file
np.save('array.npy', arr)


In [23]:
# Load from a file
loaded_arr = np.load('array.npy')


In [24]:
print (loaded_arr)

[0 1 2 3 4 5]
